import { useRef, useState } from 'react';
import ReactMarkdown from 'react-markdown';

export default function AdPackageOutput({ content, streaming, brief }) {
  const [copied, setCopied]   = useState(false);
  const [saving, setSaving]   = useState(false);
  const [saved, setSaved]     = useState(false);
  const [saveError, setSaveError] = useState('');
  const outputRef = useRef(null);

  const handleCopy = () => {
    navigator.clipboard.writeText(content).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownload = () => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `ad-package-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleSave = async () => {
    setSaving(true);
    setSaveError('');
    try {
      const res = await fetch('/api/campaigns/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ brief, packageMarkdown: content }),
      });
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error || 'Save failed.');
      }
      setSaved(true);
    } catch (err) {
      setSaveError(err.message);
    } finally {
      setSaving(false);
    }
  };

  const handleExportLaunchSheet = () => {
    // Build a structured plain-text launch sheet the dealer can hand to their agency
    const dealership = brief?.dealershipName || 'Dealership';
    const date = new Date().toLocaleDateString('en-ZA');
    const sheet = `
FACEBOOK LEAD AD — LAUNCH SHEET
Generated by OVG Ad Builder · ${date}
════════════════════════════════════════════════════════

DEALERSHIP: ${dealership}
Brand(s): ${brief?.brands || '—'}
Market: ${brief?.market || 'South Africa'}
Campaign Type: ${brief?.campaignType || '—'}
Archetype: ${brief?.archetype || 'AUTO'}
Duration: ${brief?.duration || '—'}
Daily Budget: ${brief?.dailyBudget || '—'}

────────────────────────────────────────────────────────
TARGETING PARAMETERS
────────────────────────────────────────────────────────
Geography: ${brief?.geography || '—'}
Age Range: ${brief?.ageRange || '—'}
Vehicle Ownership: ${brief?.vehicleOwnership || '—'}
Finance Status: ${brief?.financeStatus || '—'}
Existing Audiences: ${Array.isArray(brief?.existingAudiences) ? brief.existingAudiences.join(', ') : (brief?.existingAudiences || '—')}

────────────────────────────────────────────────────────
INSTANT FORM SPEC
────────────────────────────────────────────────────────
Form Type: ${brief?.formType || 'Higher Intent'}
CTA Button: ${brief?.ctaPreference || '—'}
Custom Question 1: ${brief?.customQ1 || '—'}
Custom Question 2: ${brief?.customQ2 || '—'}
OTP Phone Verification: ${brief?.otpVerification || 'Yes'}
Thank-You Message Direction: ${brief?.thankYouMessage || '—'}
Response Time Promise: ${brief?.responseTime || '5 minutes'}

────────────────────────────────────────────────────────
CREATIVE BRIEF
────────────────────────────────────────────────────────
Make / Model: ${brief?.makeModel || '—'}
Core Offer: ${brief?.coreOffer || '—'}
Headline Direction: ${brief?.headlineDirection || '—'}
Body Copy Notes: ${brief?.bodyCopyNotes || '—'}
Assets Available: ${brief?.assetsAvailable || '—'}
Visual Direction: ${brief?.visualDirection || '—'}

────────────────────────────────────────────────────────
BDC / FUNNEL SETUP
────────────────────────────────────────────────────────
BDC Team Size: ${brief?.bdcTeamSize || '—'}
BDC Hours: ${brief?.bdcHours || '—'}
Lead Routing: ${brief?.leadRouting || '—'}
CRM Integration: ${brief?.crmIntegration || '—'}
SMS Tool: ${brief?.smsTool || '—'}
Appointment System: ${brief?.appointmentSystem || '—'}

════════════════════════════════════════════════════════
AI-GENERATED AD PACKAGE
════════════════════════════════════════════════════════

${content}

════════════════════════════════════════════════════════
Generated by OVG · Facebook Automotive Ad Builder
Powered by Claude Sonnet · ${date}
`.trim();

    const blob = new Blob([sheet], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `launch-sheet-${dealership.replace(/\s+/g, '-')}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!content) return null;

  return (
    <div className="output-panel">
      <div className="output-header">
        <div className="output-title">
          {streaming ? (
            <><span className="streaming-dot" /> Generating ad package...</>
          ) : (
            <>✅ Ad Package Ready</>
          )}
        </div>
        {!streaming && (
          <div className="output-actions">
            <button className="btn-action" onClick={handleCopy}>
              {copied ? '✓ Copied!' : '📋 Copy'}
            </button>
            <button className="btn-action" onClick={handleDownload}>
              ⬇️ Download .md
            </button>
            <button className="btn-action" onClick={handleExportLaunchSheet}>
              📄 Export Launch Sheet
            </button>
            <button
              className="btn-action btn-save"
              onClick={handleSave}
              disabled={saving || saved}
            >
              {saving ? 'Saving…' : saved ? '✓ Saved' : '💾 Save Campaign'}
            </button>
          </div>
        )}
      </div>

      {saveError && (
        <div className="save-error">⚠️ {saveError}</div>
      )}

      <div className="output-body" ref={outputRef}>
        <ReactMarkdown
          components={{
            h1: ({ children }) => <h1 className="md-h1">{children}</h1>,
            h2: ({ children }) => <h2 className="md-h2">{children}</h2>,
            h3: ({ children }) => <h3 className="md-h3">{children}</h3>,
            p: ({ children }) => <p className="md-p">{children}</p>,
            ul: ({ children }) => <ul className="md-ul">{children}</ul>,
            li: ({ children }) => <li className="md-li">{children}</li>,
            strong: ({ children }) => <strong className="md-strong">{children}</strong>,
            hr: () => <hr className="md-divider" />,
            code: ({ children, className }) => {
              const isBlock = className?.includes('language-');
              return isBlock ? (
                <pre className="md-pre"><code>{children}</code></pre>
              ) : (
                <code className="md-code">{children}</code>
              );
            },
            table: ({ children }) => <table className="md-table">{children}</table>,
            th: ({ children }) => <th className="md-th">{children}</th>,
            td: ({ children }) => <td className="md-td">{children}</td>,
          }}
        >
          {content}
        </ReactMarkdown>
        {streaming && <span className="cursor-blink">▊</span>}
      </div>

      {!streaming && (
        <div className="output-footer">
          <div className="next-steps-prompt">
            <strong>Want more?</strong> You can regenerate, request Instagram Stories adaptation,
            3 headline A/B variants, or the landing page copy — just ask.
          </div>
        </div>
      )}
    </div>
  );
}
